export interface Patient {
  id: string;
  name: string;
  age: number;
  gender: string;
  patientSince: string;
  yearsAsPatient: number;
  lastVisit: string;
  diagnoses: string[];
  medications: string[];
  upcomingAppointments: { date: string; type: string }[];
  contact: { phone: string; email: string; address: string };
  mrn: string;
  insuranceProvider: string;
}

export const patients: Patient[] = [
  {
    id: "p-1",
    name: "Maria Santos",
    age: 54,
    gender: "Female",
    patientSince: "Jan 2022",
    yearsAsPatient: 4,
    lastVisit: "Feb 18, 2026",
    diagnoses: ["Stage II Breast Cancer", "Hypertension"],
    medications: ["Tamoxifen 20mg", "Lisinopril 10mg", "Ondansetron 8mg"],
    upcomingAppointments: [
      { date: "Mar 3, 2026", type: "Oncology Follow-up" },
      { date: "Mar 15, 2026", type: "Lab Work" },
    ],
    contact: { phone: "(212) 555-0101", email: "m.santos@email.com", address: "142 E 72nd St, New York, NY" },
    mrn: "MRN-20220115",
    insuranceProvider: "BlueCross BlueShield",
  },
  {
    id: "p-2",
    name: "James O'Brien",
    age: 67,
    gender: "Male",
    patientSince: "Mar 2020",
    yearsAsPatient: 6,
    lastVisit: "Feb 15, 2026",
    diagnoses: ["Stage III Non-Small Cell Lung Cancer", "COPD", "Type 2 Diabetes"],
    medications: ["Pembrolizumab IV", "Metformin 500mg", "Albuterol inhaler"],
    upcomingAppointments: [
      { date: "Feb 28, 2026", type: "Immunotherapy Infusion" },
      { date: "Mar 10, 2026", type: "CT Scan" },
    ],
    contact: { phone: "(212) 555-0102", email: "j.obrien@email.com", address: "88 Central Park West, New York, NY" },
    mrn: "MRN-20200312",
    insuranceProvider: "Aetna",
  },
  {
    id: "p-3",
    name: "Priya Patel",
    age: 41,
    gender: "Female",
    patientSince: "Sep 2023",
    yearsAsPatient: 2,
    lastVisit: "Feb 20, 2026",
    diagnoses: ["Stage I Ovarian Cancer"],
    medications: ["Carboplatin IV", "Paclitaxel IV", "Dexamethasone 4mg"],
    upcomingAppointments: [
      { date: "Mar 1, 2026", type: "Chemotherapy Cycle 4" },
    ],
    contact: { phone: "(212) 555-0103", email: "p.patel@email.com", address: "310 E 46th St, New York, NY" },
    mrn: "MRN-20230901",
    insuranceProvider: "UnitedHealthcare",
  },
  {
    id: "p-4",
    name: "Robert Chen",
    age: 72,
    gender: "Male",
    patientSince: "Jun 2019",
    yearsAsPatient: 7,
    lastVisit: "Feb 12, 2026",
    diagnoses: ["Stage IV Colorectal Cancer", "Atrial Fibrillation"],
    medications: ["FOLFOX regimen", "Bevacizumab IV", "Apixaban 5mg"],
    upcomingAppointments: [
      { date: "Feb 26, 2026", type: "Oncology Follow-up" },
      { date: "Mar 5, 2026", type: "PET Scan" },
    ],
    contact: { phone: "(212) 555-0104", email: "r.chen@email.com", address: "55 W 125th St, New York, NY" },
    mrn: "MRN-20190615",
    insuranceProvider: "Medicare",
  },
  {
    id: "p-5",
    name: "Angela Washington",
    age: 58,
    gender: "Female",
    patientSince: "Nov 2021",
    yearsAsPatient: 4,
    lastVisit: "Feb 19, 2026",
    diagnoses: ["Triple-Negative Breast Cancer", "Osteoporosis"],
    medications: ["Doxorubicin IV", "Cyclophosphamide IV", "Alendronate 70mg"],
    upcomingAppointments: [
      { date: "Mar 2, 2026", type: "Chemotherapy Cycle 6" },
      { date: "Mar 20, 2026", type: "DEXA Scan" },
    ],
    contact: { phone: "(212) 555-0105", email: "a.washington@email.com", address: "200 W 135th St, New York, NY" },
    mrn: "MRN-20211105",
    insuranceProvider: "Cigna",
  },
  {
    id: "p-6",
    name: "David Kim",
    age: 45,
    gender: "Male",
    patientSince: "Feb 2024",
    yearsAsPatient: 2,
    lastVisit: "Feb 17, 2026",
    diagnoses: ["Hodgkin Lymphoma Stage IIA"],
    medications: ["ABVD regimen", "Prednisone 40mg", "Filgrastim"],
    upcomingAppointments: [
      { date: "Mar 4, 2026", type: "Chemotherapy Cycle 3" },
    ],
    contact: { phone: "(212) 555-0106", email: "d.kim@email.com", address: "420 E 23rd St, New York, NY" },
    mrn: "MRN-20240210",
    insuranceProvider: "Anthem",
  },
  {
    id: "p-7",
    name: "Susan Miller",
    age: 63,
    gender: "Female",
    patientSince: "Aug 2020",
    yearsAsPatient: 5,
    lastVisit: "Feb 14, 2026",
    diagnoses: ["Stage II Endometrial Cancer", "Hypothyroidism"],
    medications: ["Megestrol 160mg", "Levothyroxine 75mcg"],
    upcomingAppointments: [
      { date: "Mar 7, 2026", type: "Gynecologic Oncology Follow-up" },
    ],
    contact: { phone: "(212) 555-0107", email: "s.miller@email.com", address: "780 Park Ave, New York, NY" },
    mrn: "MRN-20200820",
    insuranceProvider: "Humana",
  },
  {
    id: "p-8",
    name: "Michael Torres",
    age: 51,
    gender: "Male",
    patientSince: "Apr 2023",
    yearsAsPatient: 3,
    lastVisit: "Feb 21, 2026",
    diagnoses: ["Stage III Melanoma", "Anxiety Disorder"],
    medications: ["Nivolumab IV", "Ipilimumab IV", "Sertraline 50mg"],
    upcomingAppointments: [
      { date: "Mar 6, 2026", type: "Immunotherapy Infusion" },
      { date: "Mar 18, 2026", type: "Dermatology Check" },
    ],
    contact: { phone: "(212) 555-0108", email: "m.torres@email.com", address: "95 Christopher St, New York, NY" },
    mrn: "MRN-20230415",
    insuranceProvider: "Oscar Health",
  },
  {
    id: "p-9",
    name: "Linda Johansson",
    age: 69,
    gender: "Female",
    patientSince: "Jan 2021",
    yearsAsPatient: 5,
    lastVisit: "Feb 10, 2026",
    diagnoses: ["Stage I Pancreatic Cancer"],
    medications: ["Gemcitabine IV", "Nab-paclitaxel IV", "Pantoprazole 40mg"],
    upcomingAppointments: [
      { date: "Feb 27, 2026", type: "CT Scan" },
      { date: "Mar 8, 2026", type: "Oncology Follow-up" },
    ],
    contact: { phone: "(212) 555-0109", email: "l.johansson@email.com", address: "450 Lexington Ave, New York, NY" },
    mrn: "MRN-20210115",
    insuranceProvider: "Medicare",
  },
  {
    id: "p-10",
    name: "Carlos Rodriguez",
    age: 56,
    gender: "Male",
    patientSince: "Jul 2022",
    yearsAsPatient: 3,
    lastVisit: "Feb 16, 2026",
    diagnoses: ["Stage II Prostate Cancer"],
    medications: ["Enzalutamide 160mg", "Leuprolide injection"],
    upcomingAppointments: [
      { date: "Mar 12, 2026", type: "PSA Lab Work" },
    ],
    contact: { phone: "(212) 555-0110", email: "c.rodriguez@email.com", address: "33 Washington Sq W, New York, NY" },
    mrn: "MRN-20220718",
    insuranceProvider: "Aetna",
  },
  {
    id: "p-11",
    name: "Emma Thompson",
    age: 38,
    gender: "Female",
    patientSince: "Dec 2024",
    yearsAsPatient: 1,
    lastVisit: "Feb 22, 2026",
    diagnoses: ["Stage I Cervical Cancer"],
    medications: ["Cisplatin IV", "Fluorouracil IV"],
    upcomingAppointments: [
      { date: "Mar 1, 2026", type: "Radiation Planning" },
      { date: "Mar 14, 2026", type: "Chemoradiation Start" },
    ],
    contact: { phone: "(212) 555-0111", email: "e.thompson@email.com", address: "170 Amsterdam Ave, New York, NY" },
    mrn: "MRN-20241205",
    insuranceProvider: "BlueCross BlueShield",
  },
  {
    id: "p-12",
    name: "William Park",
    age: 74,
    gender: "Male",
    patientSince: "May 2018",
    yearsAsPatient: 8,
    lastVisit: "Feb 13, 2026",
    diagnoses: ["Chronic Lymphocytic Leukemia", "Hypertension", "Gout"],
    medications: ["Ibrutinib 420mg", "Amlodipine 5mg", "Allopurinol 300mg"],
    upcomingAppointments: [
      { date: "Mar 3, 2026", type: "Hematology Follow-up" },
      { date: "Mar 17, 2026", type: "CBC Panel" },
    ],
    contact: { phone: "(212) 555-0112", email: "w.park@email.com", address: "601 W 57th St, New York, NY" },
    mrn: "MRN-20180520",
    insuranceProvider: "Medicare",
  },
  {
    id: "p-13",
    name: "Fatima Al-Hassan",
    age: 47,
    gender: "Female",
    patientSince: "Oct 2023",
    yearsAsPatient: 2,
    lastVisit: "Feb 20, 2026",
    diagnoses: ["Stage II Thyroid Cancer"],
    medications: ["Levothyroxine 150mcg", "Calcium + Vitamin D"],
    upcomingAppointments: [
      { date: "Mar 5, 2026", type: "Thyroglobulin Lab" },
      { date: "Apr 1, 2026", type: "Neck Ultrasound" },
    ],
    contact: { phone: "(212) 555-0113", email: "f.alhassan@email.com", address: "220 E 42nd St, New York, NY" },
    mrn: "MRN-20231010",
    insuranceProvider: "UnitedHealthcare",
  },
  {
    id: "p-14",
    name: "George Nakamura",
    age: 61,
    gender: "Male",
    patientSince: "Mar 2021",
    yearsAsPatient: 5,
    lastVisit: "Feb 11, 2026",
    diagnoses: ["Stage III Bladder Cancer", "Type 2 Diabetes"],
    medications: ["Atezolizumab IV", "Metformin 1000mg", "Glipizide 5mg"],
    upcomingAppointments: [
      { date: "Feb 28, 2026", type: "Cystoscopy" },
      { date: "Mar 20, 2026", type: "Immunotherapy Infusion" },
    ],
    contact: { phone: "(212) 555-0114", email: "g.nakamura@email.com", address: "85 Mercer St, New York, NY" },
    mrn: "MRN-20210310",
    insuranceProvider: "Cigna",
  },
  {
    id: "p-15",
    name: "Catherine Murphy",
    age: 52,
    gender: "Female",
    patientSince: "Aug 2022",
    yearsAsPatient: 3,
    lastVisit: "Feb 19, 2026",
    diagnoses: ["Stage II Non-Hodgkin Lymphoma"],
    medications: ["R-CHOP regimen", "Prednisone 60mg", "Acyclovir 400mg"],
    upcomingAppointments: [
      { date: "Mar 2, 2026", type: "Chemotherapy Cycle 5" },
    ],
    contact: { phone: "(212) 555-0115", email: "c.murphy@email.com", address: "333 E 69th St, New York, NY" },
    mrn: "MRN-20220815",
    insuranceProvider: "Anthem",
  },
  {
    id: "p-16",
    name: "Ahmed Hassan",
    age: 59,
    gender: "Male",
    patientSince: "Jun 2021",
    yearsAsPatient: 5,
    lastVisit: "Feb 18, 2026",
    diagnoses: ["Stage IV Renal Cell Carcinoma"],
    medications: ["Sunitinib 50mg", "Amlodipine 10mg", "Omeprazole 20mg"],
    upcomingAppointments: [
      { date: "Mar 4, 2026", type: "Abdominal CT" },
      { date: "Mar 11, 2026", type: "Oncology Follow-up" },
    ],
    contact: { phone: "(212) 555-0116", email: "a.hassan@email.com", address: "150 W 85th St, New York, NY" },
    mrn: "MRN-20210620",
    insuranceProvider: "Humana",
  },
  {
    id: "p-17",
    name: "Rachel Green",
    age: 44,
    gender: "Female",
    patientSince: "Nov 2024",
    yearsAsPatient: 1,
    lastVisit: "Feb 21, 2026",
    diagnoses: ["Stage I Breast Cancer (HER2+)"],
    medications: ["Trastuzumab IV", "Pertuzumab IV", "Docetaxel IV"],
    upcomingAppointments: [
      { date: "Mar 6, 2026", type: "Echocardiogram" },
      { date: "Mar 13, 2026", type: "Targeted Therapy Infusion" },
    ],
    contact: { phone: "(212) 555-0117", email: "r.green@email.com", address: "425 E 58th St, New York, NY" },
    mrn: "MRN-20241112",
    insuranceProvider: "Oscar Health",
  },
  {
    id: "p-18",
    name: "Thomas Wright",
    age: 70,
    gender: "Male",
    patientSince: "Feb 2020",
    yearsAsPatient: 6,
    lastVisit: "Feb 14, 2026",
    diagnoses: ["Multiple Myeloma", "Chronic Kidney Disease Stage 2"],
    medications: ["Lenalidomide 25mg", "Dexamethasone 40mg", "Bortezomib SC"],
    upcomingAppointments: [
      { date: "Mar 1, 2026", type: "Bone Marrow Biopsy" },
      { date: "Mar 15, 2026", type: "Nephrology Consult" },
    ],
    contact: { phone: "(212) 555-0118", email: "t.wright@email.com", address: "275 Greenwich St, New York, NY" },
    mrn: "MRN-20200205",
    insuranceProvider: "Medicare",
  },
  {
    id: "p-19",
    name: "Nina Volkov",
    age: 36,
    gender: "Female",
    patientSince: "Jan 2025",
    yearsAsPatient: 1,
    lastVisit: "Feb 22, 2026",
    diagnoses: ["Stage II Sarcoma (Soft Tissue)"],
    medications: ["Doxorubicin IV", "Ifosfamide IV", "Mesna IV"],
    upcomingAppointments: [
      { date: "Mar 3, 2026", type: "MRI Extremity" },
      { date: "Mar 10, 2026", type: "Surgical Oncology Consult" },
    ],
    contact: { phone: "(212) 555-0119", email: "n.volkov@email.com", address: "500 W 43rd St, New York, NY" },
    mrn: "MRN-20250115",
    insuranceProvider: "BlueCross BlueShield",
  },
  {
    id: "p-20",
    name: "Harold Freeman",
    age: 76,
    gender: "Male",
    patientSince: "Apr 2019",
    yearsAsPatient: 7,
    lastVisit: "Feb 10, 2026",
    diagnoses: ["Stage III Esophageal Cancer", "GERD", "Hypertension"],
    medications: ["Carboplatin IV", "Paclitaxel IV", "Omeprazole 40mg", "Losartan 50mg"],
    upcomingAppointments: [
      { date: "Feb 27, 2026", type: "Radiation Therapy" },
      { date: "Mar 12, 2026", type: "Endoscopy" },
    ],
    contact: { phone: "(212) 555-0120", email: "h.freeman@email.com", address: "180 Riverside Dr, New York, NY" },
    mrn: "MRN-20190410",
    insuranceProvider: "Medicare",
  },
  {
    id: "p-21",
    name: "Lisa Chang",
    age: 49,
    gender: "Female",
    patientSince: "Sep 2022",
    yearsAsPatient: 3,
    lastVisit: "Feb 17, 2026",
    diagnoses: ["Stage II Gastric Cancer"],
    medications: ["FLOT regimen", "Ondansetron 8mg", "Dexamethasone 8mg"],
    upcomingAppointments: [
      { date: "Mar 5, 2026", type: "Chemotherapy Cycle 4" },
      { date: "Mar 22, 2026", type: "Upper GI Series" },
    ],
    contact: { phone: "(212) 555-0121", email: "l.chang@email.com", address: "40 E 89th St, New York, NY" },
    mrn: "MRN-20220905",
    insuranceProvider: "Aetna",
  },
  {
    id: "p-22",
    name: "Patrick Sullivan",
    age: 64,
    gender: "Male",
    patientSince: "Dec 2020",
    yearsAsPatient: 5,
    lastVisit: "Feb 15, 2026",
    diagnoses: ["Stage II Head & Neck Cancer (Oropharyngeal)"],
    medications: ["Cetuximab IV", "Radiation therapy", "Magic mouthwash"],
    upcomingAppointments: [
      { date: "Mar 1, 2026", type: "Radiation Session" },
      { date: "Mar 8, 2026", type: "Speech Pathology" },
    ],
    contact: { phone: "(212) 555-0122", email: "p.sullivan@email.com", address: "715 Amsterdam Ave, New York, NY" },
    mrn: "MRN-20201215",
    insuranceProvider: "Cigna",
  },
  {
    id: "p-23",
    name: "Dorothy Nguyen",
    age: 55,
    gender: "Female",
    patientSince: "Jul 2023",
    yearsAsPatient: 3,
    lastVisit: "Feb 20, 2026",
    diagnoses: ["Stage III Ovarian Cancer", "Deep Vein Thrombosis"],
    medications: ["Carboplatin IV", "Paclitaxel IV", "Bevacizumab IV", "Enoxaparin 40mg"],
    upcomingAppointments: [
      { date: "Mar 2, 2026", type: "Chemotherapy Cycle 6" },
      { date: "Mar 16, 2026", type: "CA-125 Lab" },
    ],
    contact: { phone: "(212) 555-0123", email: "d.nguyen@email.com", address: "60 E 96th St, New York, NY" },
    mrn: "MRN-20230710",
    insuranceProvider: "UnitedHealthcare",
  },
  {
    id: "p-24",
    name: "Frank DiMaggio",
    age: 68,
    gender: "Male",
    patientSince: "May 2021",
    yearsAsPatient: 5,
    lastVisit: "Feb 13, 2026",
    diagnoses: ["Stage II Liver Cancer (HCC)", "Hepatitis C (treated)", "Cirrhosis"],
    medications: ["Sorafenib 400mg", "Lactulose 30ml", "Spironolactone 100mg"],
    upcomingAppointments: [
      { date: "Mar 4, 2026", type: "Abdominal MRI" },
      { date: "Mar 18, 2026", type: "Hepatology Follow-up" },
    ],
    contact: { phone: "(212) 555-0124", email: "f.dimaggio@email.com", address: "225 E 106th St, New York, NY" },
    mrn: "MRN-20210520",
    insuranceProvider: "Humana",
  },
];
